export const GET_POKEDEX_DETAILS_FETCHING = "GET_POKEDEX_DETAILS_FETCHING";
export const GET_POKEDEX_DETAILS_SUCCESS = "GET_POKEDEX_DETAILS_SUCCESS";
export const GET_POKEDEX_DETAILS_ERROR = "GET_POKEDEX_DETAILS_ERROR";

export const SET_POKEMON_NAME_DETAILS = "SET_POKEMON_NAME_DETAILS";

export const GET_POKEDEX_SEARCH_FETCHING = "GET_POKEDEX_SEARCH_FETCHING";
export const GET_POKEDEX_SEARCH_SUCCESS = "GET_POKEDEX_SEARCH_SUCCESS";
export const GET_POKEDEX_SEARCH_ERROR  = "GET_POKEDEX_SEARCH_ERROR";

export const SET_POKEMON_NAME_SEARCH = "SET_POKEMON_NAME_SEARCH";
export const SET_POKEMON_CONFIG_SEARCH = "SET_POKEMON_CONFIG_SEARCH";
export const SET_POKEMON_CONFIG_DEFAULT_SEARCH = "SET_POKEMON_CONFIG_DEFAULT_SEARCH";

export const CLEAN_POKEDEX = "CLEAN_POKEDEX";